Avaliação/Controllers/MenuIniController.cs
using Avaliação.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Avaliação.Controllers
{
    public class MenuIniController : Controller
    {

        IHttpContextAccessor HttpContextAccessor;
        public MenuIniController(IHttpContextAccessor httpContextAccessor)
        {

            HttpContextAccessor = httpContextAccessor;



        }
        [HttpGet]
        public IActionResult Index(int? id)
        {



            if (id != null)
            {
                if (id == 0)
                {
                    HttpContext.Session.SetString("IdUsuarioLogado", string.Empty);
                    HttpContext.Session.SetString("NomeUsuarioColaborador", string.Empty);
                    HttpContext.Session.SetString("NomeUsuarioSetor", string.Empty);
                    HttpContext.Session.SetString("NomeUsuarioTurno", string.Empty);
                    HttpContext.Session.SetString("NomeUsuarioGestor", string.Empty);
                    HttpContext.Session.SetString("NomeUsuarioEmail", string.Empty);
                    HttpContext.Session.SetString("NomeUsuarioEmailGestor", string.Empty);
                    HttpContext.Session.SetString("NomeUsuarioEmailRh", string.Empty);


                }
            }

            return View();
        }

        [HttpPost]
        public IActionResult ValidarUser(MenuIniModel menu)
        {
            bool login = menu.ValidarUser();
            bool log = menu.ValidarUser1();
            bool loger = menu.ValidarUser2();
            bool logers = menu.ValidarUser3();
            bool logSV = menu.ValidarSV();

            if (login)
            {

                HttpContext.Session.SetString("NomeUsuarioColaborador", menu.Nome);
                HttpContext.Session.SetString("NomeUsuarioMatricula", menu.Matricula);
                // HttpContext.Session.SetString("NomeUsuarioCargo", usuario.Cargo);
                // HttpContext.Session.SetString("NomeUsuarioUnidade", usuario.Unidade);
                HttpContext.Session.SetString("IdUsuarioLogado", menu.Id.ToString());

                return RedirectToAction("NegociosGestor", "Competencia");
            }


            if (log)

            {

                HttpContext.Session.SetString("NomeUsuarioColaborador", menu.Nome);
                HttpContext.Session.SetString("NomeUsuarioMatricula", menu.Matricula);
                // HttpContext.Session.SetString("NomeUsuarioCargo", usuario.Cargo);
                //  HttpContext.Session.SetString("NomeUsuarioUnidade", usuario.Unidade);
                HttpContext.Session.SetString("IdUsuarioLogado", menu.Id.ToString());
                return RedirectToAction("NegociosEspec", "Competencia");
            }

            if (loger)
            {

                HttpContext.Session.SetString("NomeUsuarioColaborador", menu.Nome);
                HttpContext.Session.SetString("NomeUsuarioMatricula", menu.Matricula);
                //  HttpContext.Session.SetString("NomeUsuarioCargo", usuario.Cargo);
                //  HttpContext.Session.SetString("NomeUsuarioUnidade", usuario.Unidade);
                HttpContext.Session.SetString("IdUsuarioLogado", menu.Id.ToString());
                return RedirectToAction("NegociosGLTL", "Competencia");
            }
            if (logers)
            {

                HttpContext.Session.SetString("NomeUsuarioColaborador", menu.Nome);
                HttpContext.Session.SetString("NomeUsuarioMatricula", menu.Matricula);
                //  HttpContext.Session.SetString("NomeUsuarioCargo", usuario.Cargo);
                //  HttpContext.Session.SetString("NomeUsuarioUnidade", usuario.Unidade);
                HttpContext.Session.SetString("IdUsuarioLogado", menu.Id.ToString());
                return RedirectToAction("NegociosAssist", "Competencia");
            }
            if (logSV)
            {

                HttpContext.Session.SetString("NomeUsuarioColaborador", menu.Nome);
                HttpContext.Session.SetString("NomeUsuarioMatricula", menu.Matricula);
                //  HttpContext.Session.SetString("NomeUsuarioCargo", usuario.Cargo);
                //  HttpContext.Session.SetString("NomeUsuarioUnidade", usuario.Unidade);
                HttpContext.Session.SetString("IdUsuarioLogado", menu.Id.ToString());
                return RedirectToAction("NegociosGestor", "Competencia");
            }
            else
            {
                TempData["MensagemLoginInvalido"] = "Colaborador não Cadastrado";
                return RedirectToAction("Index", "Menuini");
            }
        }


        [HttpGet]
        public IActionResult Registrar()
        {
            return View();
        }

        public IActionResult Sucesso()
        {
            return View();
        }

    }
}

Avaliação/Views/MenuIni/Index.cshtml
@model MenuIniModel
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor HttpContextAccessor

@{
    Layout = "../Shared/_LayoutAvaliar.cshtml";
}

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<div class="container" style="background-color:rgba(239, 239, 239, 0.99); border-radius: 10px; padding:20px; width:300px;">
    @{
        try
        {
            if (TempData["MensagemLoginInvalido"].ToString() != null)
            {
                <div class="alert alert-danger">
                    <strong>Atenção!</strong> @TempData["MensagemLoginInvalido"]
                </div>
            }
        }
        catch { }
    }




    <form asp-controller="MenuIni" asp-action="ValidarUser">



        <div class="form-group">
            <label for="pwd">Nome do Gestor:</label>
            <input type="text" class="form-control" value="@HttpContextAccessor.HttpContext.Session.GetString("NomeUsuarioLogado") " asp-for="NomeGestor">
        </div>
        <div class="form-group">
            <label for="Nome">Digite a Matricula do Colaborador:</label>
            <input type="text" class="form-control" value="@HttpContextAccessor.HttpContext.Session.GetString("NomeUsuarioMatricula") " asp-for="Matricula">
        </div>
        <div class="checkbox">
            <label style="font-size:150%;background-color:gainsboro;color:red"><b>Avaliação de Negócios<b /></label>
        </div>
        <button type="submit" class="btn btn-primary">Pesquisar</button>


    </form>